### ISSUE TITLE
Logic Nodes Trait blocks constructor

### ISSUE THREAD

**Issue by Devination** [luboslenco/zblend#7]
If you add a "Nodes" trait to the default cube and create a NodeTree for it, the cube will not show up in game (HTML5 build)

In the Browser console of FireFox I get this Warning: 
TypeError: asm.js type error: Disabled by javascript.options.asmjs in about:config ammo.js

And this Error:
TypeError: cl is not a constructor kha.js:352:0

**Comment by luboslenco** [comment]
Should be fixed now, added this check-box in project panel which makes sure nodes will be built when compiling project:
![screen shot 2015-04-16 at 09 09 14](https://cloud.githubusercontent.com/assets/3685704/7175745/50440376-e418-11e4-9432-9058a1e0d00d.png)

Thanks for feedback!

**Comment by Devination** [comment]
Awesome, that works thanks!

**Comment by Devination** [comment]
On the subject of logic nodes, could you point me to which files I'd need to modify to create new nodes? I modified zblend_nodes.py and got a new node to show up, then I used TransformNode.hx as a template to make the logic for my new node. But nothing seemed to happen.

It was a simple node, just had 2 float values in it, no inputs, only outputs. It built fine with no errors. But the value outputs of the node always seemed to be 0, no matter what I set them to.

I also tried exposing the FloteNode.hx in zblend_nodes.py. The Float node showed up but again, no matter what I set the value to it always acted as though it was 0. Any idea what I'm missing?

**Comment by luboslenco** [comment]
Hm that sounds like all what should be needed. Can you show more about what did you do?

I added SineNode which just outputs sine value:
python code: https://github.com/luboslenco/zblend_blender/commit/21544b6f846946d60e4b965d121b1b5f3bb7fc72
haxe code: https://github.com/luboslenco/zblend/commit/570d5e08eb95927ff1985bb4473e04b7f6df0eff

![sine](https://cloud.githubusercontent.com/assets/3685704/7205981/8f73d38a-e52d-11e4-9462-bd04366c8735.png)

Need to actually split nodes in python into separate files to make it a little cleaner.

**Comment by Devination** [comment]
Ah silly me, I forgot to add it to the classes array in the python file :p

But now theres a new error stopping the HTML game from runnning if I have a 'Nodes' trait enabled on an object: "too much recursion kha.js:15088:0"

I've discarded all my changes and Fetched to make sure my changes weren't mucking it up

**Comment by Devination** [comment]
Sorry, I'm running into all sorts of issues :( I started another project from your my_project.blend template. Got around that error and was able to build but ran into 3 new issues... I'll close this one and open new ones for those.
