### ISSUE TITLE
Uncaught Error kha.js:2064 - Stops at loading bar

### ISSUE THREAD

**Issue by Devination** [luboslenco/zblend#8]
After building a working project for HTML5 a few times, eventually the build will not run and the web console will have this error:

Firefox: "Error:  &lt;unknown&gt;"

Chrome: "Uncaught Error kha.js:2064"
haxe_Unserializer.unserialize	@	kha.js:2064
haxe_Unserializer.run	@	kha.js:1804
kha_StorageFile.readObject	@	kha.js:6075
zblend_sys_Storage	@	kha.js:14149
$extend.loadingFinished	@	kha.js:11507
f	@	kha.js:15975
kha_Loader.checkComplete	@	kha.js:4578
(anonymous function)	@	kha.js:4468
$extend.loadBlob.request.onreadystatechange	@	kha.js:8953

The issue appears to be related to Logic Nodes. I had a Vector with a value in y plugged into a Transform node. That worked fine. Once I added a value to x as well as y, then the errors above happened. Once that error happens, you can't reverse it. I tried setting the vector x back to 0, deleting the nodes, deleting the 'Nodes' trait from the object, deleting the Object. Nothing worked.
![capture](https://cloud.githubusercontent.com/assets/8147765/7217805/f7367cd4-e5fa-11e4-98db-a8de40e2df36.PNG)

**Comment by luboslenco** [comment]
Should also be fixed now, there were some updates to Kha and Storage for saving data got broken.

On the plus side, Kha is now only about 175mb so starting from scratch is much much faster.

Sorry that it's constantly broken, it's hard to keep up as everything gets changed so often. Hopefully it gets more stable as the platform matures. :)

**Comment by Devination** [comment]
Awesome thanks :) I'm excited about the project, just hoping to help anyway I can

**Comment by luboslenco** [comment]
Thanks for encouragement! :)
